# Explicit Nixpkgs packages to ensure pip is available
providers = ["node", "python"]

[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

# Ensure pip is available by explicitly including it
[nixpkgs]
packages = ["nodejs_18", "python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.build]
# Add a step to ensure pip is accessible
cmds = [
  "cd frontend && npm install && npm run build",
  # Attempt to install pip tools for the specific python3.11 if it's not present globally
  "python3.11 -m ensurepip --default-pip || true", # ensure pip is there
  "python3.11 -m pip install --upgrade pip setuptools", # upgrade pip and setuptools
  "cd backend && python3.11 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "cd backend && python3.11 import_data.py && python3.11 run.py"