# Let the Python provider handle pip installation
providers = ["node", "python"]

[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

[phases.setup]
cmds = [
  # Verify Python and pip are available
  "which python3",
  "which pip3",
  "python3 --version",
  "pip3 --version"
]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "cd ..",
  # Use pip3 instead of python3 -m pip
  "cd backend && pip3 install -r requirements.txt"
]

[phases.start]
cmd = "cd backend && python3 import_data.py && python3 run.py"

[build]
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && pip3 install -r requirements.txt"

[deploy]
startCommand = "cd backend && python3 import_data.py && python3 run.py"