# Try using nix-env to install pip system-wide
providers = ["node", "python"]

[variables]
NODE_VERSION = "18" 
PYTHON_VERSION = "3.11"

[phases.setup]
cmds = [
  # Install pip using nix-env
  "nix-env -iA nixpkgs.python311Packages.pip nixpkgs.python311Packages.setuptools nixpkgs.python311Packages.wheel",
  # Verify installation
  "which python3",
  "python3 --version",
  "python3 -m pip --version || echo 'pip module not available'",
  "find /nix -name 'pip' -type f 2>/dev/null | head -5"
]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build", 
  "cd ..",
  # Try to find and use pip directly
  "PIPPATH=$(find /nix -name 'pip' -type f -executable 2>/dev/null | head -1)",
  "echo \"Found pip at: $PIPPATH\"",
  "cd backend && $PIPPATH install -r requirements.txt"
]

[phases.start]
cmd = "cd backend && python3 import_data.py && python3 run.py"

[build] 
buildCommand = "nix-env -iA nixpkgs.python311Packages.pip && cd frontend && npm install && npm run build && cd ../backend && PIPPATH=$(find /nix -name 'pip' -type f -executable 2>/dev/null | head -1) && $PIPPATH install -r requirements.txt"

[deploy]
startCommand = "cd backend && python3 import_data.py && python3 run.py"