# Fix: providers should be an array, not a map
providers = ["node", "python"]

[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "cd backend && pip install -r requirements.txt"
]

[phases.start]
cmd = "cd backend && python import_data.py && python run.py"