# Explicit Nixpkgs packages to ensure pip is available
providers = ["node", "python"]

[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

# Ensure pip is available by explicitly including it
[nixpkgs]
packages = ["nodejs_18", "python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  # Go back to the root directory before running backend commands
  "cd ..",
  # Explicitly ensure pip and setuptools are healthy for python3
  "python3 -m pip install --upgrade pip setuptools",
  # Now install backend requirements using the verified pip
  "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "cd backend && python3 import_data.py && python3 run.py"