[build]
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && python3 -m pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python3 import_data.py && python3 run.py"